app:
  hello: "Hello from local"
  secret: "${app_secret:local}"

server:
  shutdown: graceful

spring:
  application:
    name: spring-k8s-workshop

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: metrics,health,info,env,prometheus
  metrics:
    tags:
      application: ${spring.application.name}

---
spring:
  config:
    activate.on-cloud-platform: kubernetes
    import: "optional:configtree:/etc/config/*/,optional:file:./config/"

example.activation.property: "This should be visible if platform is k8s:>"