app:
  hello: "Hello from local"
  secret: "${K8S_SECRET:default}"

server:
  shutdown: graceful

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: metrics,health,info,env,prometheus