apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-k8s-workshop
  name: spring-k8s-workshop
  namespace: spring-k8s-workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-k8s-workshop
  strategy: {}
  template:
    metadata:
      labels:
        app: spring-k8s-workshop
    spec:
      containers:
      - image: spring-k8s-workshop:0.0.1-SNAPSHOT
        name: spring-k8s-workshop
        lifecycle:
          preStop:
            exec:
              command: [ "sh", "-c", "sleep 10" ]
        resources:
          requests:
            cpu: 800m
#            memory: 4048Mi
#          limits:
            #cpu: 1600m
#            memory: 4048Mi
        ports:
          - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 300
          timeoutSeconds: 20
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
        env:
          - name: K8S_SECRET
            valueFrom:
              secretKeyRef:
                name: spring-k8s-workshop-secret
                key: secret
          - name: APP_HELLO
            valueFrom:
              configMapKeyRef:
                name: spring-k8s-workshop-configmap
                key: app-hello

