apiVersion: v1
kind: Service
metadata:
  namespace: spring-k8s-workshop
  name: spring-k8s-workshop
  labels:
    app: spring-k8s-workshop
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: spring-k8s-workshop
  type: ClusterIP
