apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-k8s-workshop
  name: spring-k8s-workshop
  namespace: spring-k8s-workshop
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-k8s-workshop
  type: ClusterIP
